"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { LoadingButton } from "@/components/ui/loading-button"
import { PageLoader } from "@/components/ui/page-loader"
import { useLoading } from "@/hooks/use-loading"
import { useToast } from "@/hooks/use-toast"
import { DollarSign, ShoppingCart, Users, Package, TrendingUp, TrendingDown, RefreshCw, Download } from "lucide-react"
import apiClient from "@/lib/apiClient"

export function DashboardHome() {
  const [dashboardData, setDashboardData] = useState<any>(null)
  const [initialLoading, setInitialLoading] = useState(true)

  const { loading: refreshLoading, withLoading: withRefreshLoading } = useLoading()
  const { loading: exportLoading, withLoading: withExportLoading } = useLoading()
  const { toast } = useToast()


  const getTopProducts = async () => {
    try {
      const data = await apiClient.get('/products/best-selling')
      console.log("data", data)
    } catch (error) {
      console.log("error", error)

    }
  }

  useEffect(() => {
    getTopProducts()
  }, [])
  // Simulate initial data loading
  useEffect(() => {
    const loadDashboardData = async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000))
      setDashboardData({
        todaySales: 2847.5,
        totalTransactions: 156,
        totalCustomers: 1247,
        lowStockItems: 8,
        salesGrowth: 12.5,
        transactionGrowth: -2.3,
        customerGrowth: 8.7,
        inventoryGrowth: -15.2,
        recentSales: [
          { id: "TXN156", time: "14:30", amount: 45.5, customer: "John Doe", status: "completed" },
          { id: "TXN155", time: "14:25", amount: 78.2, customer: "Jane Smith", status: "completed" },
          { id: "TXN154", time: "14:20", amount: 32.1, customer: "Walk-in", status: "completed" },
          { id: "TXN153", time: "14:15", amount: 156.75, customer: "Mike Johnson", status: "completed" },
          { id: "TXN152", time: "14:10", amount: 89.3, customer: "Sarah Wilson", status: "refunded" },
        ],
        topProducts: [
          { name: "Banana", sales: 45, revenue: 33.75, trend: "up" },
          { name: "Milk", sales: 32, revenue: 112.0, trend: "up" },
          { name: "Bread", sales: 28, revenue: 70.0, trend: "down" },
          { name: "Apple", sales: 25, revenue: 30.0, trend: "up" },
          { name: "Orange", sales: 22, revenue: 13.2, trend: "stable" },
        ],
      })
      setInitialLoading(false)
    }

    loadDashboardData()
  }, [])

  const handleRefreshData = async () => {
    await withRefreshLoading(async () => {
      try {
        // Simulate data refresh
        await new Promise((resolve) => setTimeout(resolve, 1500))

        // Update some random values to show refresh
        setDashboardData((prev: any) => ({
          ...prev,
          todaySales: prev.todaySales + Math.random() * 100,
          totalTransactions: prev.totalTransactions + Math.floor(Math.random() * 10),
          lastRefresh: new Date().toLocaleTimeString(),
        }))

        toast({
          variant: "success",
          title: "Data Refreshed",
          description: "Dashboard data has been updated successfully",
        })
      } catch (error) {
        toast({
          variant: "destructive",
          title: "Refresh Failed",
          description: "Could not refresh dashboard data",
        })
      }
    })
  }

  const generateReport = (reportType: string) => {
    const reportData = {
      type: reportType,
      generatedAt: new Date().toISOString(),
      data: dashboardData,
      summary: {
        totalSales: dashboardData.todaySales,
        totalTransactions: dashboardData.totalTransactions,
        averageTransaction: dashboardData.todaySales / dashboardData.totalTransactions,
        topProduct: dashboardData.topProducts[0]?.name || "N/A",
      },
    }

    const reportContent = `
MANPASAND POS SYSTEM - ${reportType.toUpperCase()} REPORT
Generated: ${new Date(reportData.generatedAt).toLocaleString()}
================================================

SUMMARY:
- Total Sales: $${reportData.summary.totalSales.toFixed(2)}
- Total Transactions: ${reportData.summary.totalTransactions}
- Average Transaction: $${reportData.summary.averageTransaction.toFixed(2)}
- Top Product: ${reportData.summary.topProduct}

RECENT TRANSACTIONS:
${dashboardData.recentSales
        .map((sale: any) => `${sale.id} - ${sale.customer} - $${sale.amount.toFixed(2)} - ${sale.status}`)
        .join("\n")}

TOP PRODUCTS:
${dashboardData.topProducts
        .map(
          (product: any, index: number) =>
            `${index + 1}. ${product.name} - ${product.sales} units - $${product.revenue.toFixed(2)}`,
        )
        .join("\n")}

================================================
Report generated by MANPASAND POS System
    `

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${reportType}-report-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleExportReport = async () => {
    await withExportLoading(async () => {
      try {
        // Simulate report generation
        await new Promise((resolve) => setTimeout(resolve, 2000))

        generateReport("daily-sales")

        toast({
          variant: "success",
          title: "Report Exported",
          description: "Daily sales report has been downloaded successfully",
        })
      } catch (error) {
        toast({
          variant: "destructive",
          title: "Export Failed",
          description: "Could not generate the report",
        })
      }
    })
  }

  if (initialLoading) {
    return <PageLoader message="Loading dashboard..." />
  }

  const formatCurrency = (amount: number) => `$${amount.toFixed(2)}`
  const formatGrowth = (growth: number) => `${growth >= 0 ? "+" : ""}${growth.toFixed(1)}%`

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
          <p className="text-gray-600">
            Welcome back! Here's what's happening today.
            {dashboardData.lastRefresh && (
              <span className="text-sm text-green-600 ml-2">Last updated: {dashboardData.lastRefresh}</span>
            )}
          </p>
        </div>
        <div className="flex space-x-2">
          <LoadingButton
            variant="outline"
            onClick={handleRefreshData}
            loading={refreshLoading}
            loadingText="Refreshing..."
          >
            <RefreshCw className="h-4 w-4 mr-2" />
            Refresh
          </LoadingButton>
          <LoadingButton onClick={handleExportReport} loading={exportLoading} loadingText="Generating...">
            <Download className="h-4 w-4 mr-2" />
            Export Report
          </LoadingButton>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card className="hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Today's Sales</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatCurrency(dashboardData.todaySales)}</div>
            <div className="flex items-center space-x-1 text-xs text-muted-foreground">
              {dashboardData.salesGrowth >= 0 ? (
                <TrendingUp className="h-3 w-3 text-green-600" />
              ) : (
                <TrendingDown className="h-3 w-3 text-red-600" />
              )}
              <span className={dashboardData.salesGrowth >= 0 ? "text-green-600" : "text-red-600"}>
                {formatGrowth(dashboardData.salesGrowth)}
              </span>
              <span>from yesterday</span>
            </div>
          </CardContent>
        </Card>

        <Card className="hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Transactions</CardTitle>
            <ShoppingCart className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{dashboardData.totalTransactions}</div>
            <div className="flex items-center space-x-1 text-xs text-muted-foreground">
              {dashboardData.transactionGrowth >= 0 ? (
                <TrendingUp className="h-3 w-3 text-green-600" />
              ) : (
                <TrendingDown className="h-3 w-3 text-red-600" />
              )}
              <span className={dashboardData.transactionGrowth >= 0 ? "text-green-600" : "text-red-600"}>
                {formatGrowth(dashboardData.transactionGrowth)}
              </span>
              <span>from yesterday</span>
            </div>
          </CardContent>
        </Card>

        <Card className="hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Customers</CardTitle>
            <Users className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{dashboardData.totalCustomers.toLocaleString()}</div>
            <div className="flex items-center space-x-1 text-xs text-muted-foreground">
              {dashboardData.customerGrowth >= 0 ? (
                <TrendingUp className="h-3 w-3 text-green-600" />
              ) : (
                <TrendingDown className="h-3 w-3 text-red-600" />
              )}
              <span className={dashboardData.customerGrowth >= 0 ? "text-green-600" : "text-red-600"}>
                {formatGrowth(dashboardData.customerGrowth)}
              </span>
              <span>this month</span>
            </div>
          </CardContent>
        </Card>

        <Card className="hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Low Stock Items</CardTitle>
            <Package className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">{dashboardData.lowStockItems}</div>
            <div className="flex items-center space-x-1 text-xs text-muted-foreground">
              {dashboardData.inventoryGrowth >= 0 ? (
                <TrendingUp className="h-3 w-3 text-green-600" />
              ) : (
                <TrendingDown className="h-3 w-3 text-red-600" />
              )}
              <span className={dashboardData.inventoryGrowth >= 0 ? "text-green-600" : "text-red-600"}>
                {formatGrowth(dashboardData.inventoryGrowth)}
              </span>
              <span>from last week</span>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recent Sales */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              Recent Sales
              <Badge variant="secondary">{dashboardData.recentSales.length} transactions</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {dashboardData.recentSales.map((sale: any) => (
                <div
                  key={sale.id}
                  className="flex items-center justify-between p-3 border rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <div>
                    <div className="font-medium">{sale.id}</div>
                    <div className="text-sm text-gray-500">
                      {sale.customer} • {sale.time}
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="font-medium">{formatCurrency(sale.amount)}</div>
                    <Badge
                      variant={sale.status === "completed" ? "default" : "destructive"}
                      className={sale.status === "completed" ? "bg-green-100 text-green-800" : ""}
                    >
                      {sale.status}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Top Products */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              Top Products
              <Badge variant="secondary">Today's best sellers</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {dashboardData.topProducts.map((product: any, index: number) => (
                <div
                  key={product.name}
                  className="flex items-center justify-between p-3 border rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <div className="flex items-center space-x-3">
                    <Badge variant="secondary">#{index + 1}</Badge>
                    <div>
                      <div className="font-medium flex items-center space-x-2">
                        <span>{product.name}</span>
                        {product.trend === "up" && <TrendingUp className="h-3 w-3 text-green-600" />}
                        {product.trend === "down" && <TrendingDown className="h-3 w-3 text-red-600" />}
                      </div>
                      <div className="text-sm text-gray-500">{product.sales} units sold</div>
                    </div>
                  </div>
                  <div className="font-medium">{formatCurrency(product.revenue)}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
